image: gitlab/dind

stages:
  - deploy

services:
  - docker:dind
  
deploy:
  stage: deploy
  script:
    - ls
    - docker build -t state-structure-front .
    - docker run -d -p 4200:8080 state-structure-front
