image: docker:latest

services:
  - name: docker:dind
  entrypoint: ["env", "-u", "DOCKER_HOST"]
  command: ["dockerd-entrypoint.sh"]
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  
stages:
  - deploy
deploy:
  stage: deploy
  script:
    - docker build -t state-structure-front .
    - docker run -d -p 4200:8080 state-structure-front
