//GlobalStore

export const SET_MODAL_NAME = "SET_MODAL_NAME";
export const SET_LOADING = "SET_LOADING";

//TreeStore
export const SET_TREE = "SET_TREE";
export const SET_TREE_SAFE = "SET_TREE_SAFE";
export const INSERT_NODE_TO_TREE = "INSERT_NODE_TO_TREE";
export const UPDATE_TREE = "UPDATE_TREE";
export const DELETE_NODE = "DELETE_NODE";
export const DELETE_POSITION_FROM_NODE = "DELETE_POSITION_FROM_NODE";
export const SET_DRAG_TREE = "SET_DRAG_TREE";
export const INSERT_POSITION_TO_NODE = "INSERT_POSITION_TO_NODE";
export const SET_PLUS_SELECTED_NODE = "SET_PLUS_SELECTED_NODE";
export const ADD_SUBDIVISION = "ADD_SUBDIVISION";
export const CHANGE_SUBDIVISION = "CHANGE_SUBDIVISION";
export const CHANGE_POSITION = "CHANGE_POSITION";
export const DELETE_ROLE_FROM_TREE = "DELETE_ROLE_FROM_TREE";
export const RELOAD_TREE = "RELOAD_TREE";
export const SET_LANGUAGE = "SET_LANGUAGE";
//SystemStore
export const SET_USER_TYPE = "SET_USER_TYPE";
export const SET_WEBSOCKET_STATE = "SET_WEBSOCKET_STATE";
export const SET_LOGGINED = "SET_LOGGINED";
export const CHECK_IS_LOGGINED = "CHECK_IS_LOGGINED";
//HomeStpre
export const SET_POSITIONS = "SET_POSITIONS";
export const ADD_POSITION = "ADD_POSITION";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const SET_TEMP_EMPLOYEE_FOR_REPLACEMENT =
  "SET_TEMP_EMPLOYEE_FOR_REPLACEMENT";
export const DELETE_POSITION = "DELETE_POSITION";
export const GET_FILTERED_POSITIONS = "GET_FILTERED_POSITIONS";
export const SET_UNLOCK = "SET_UNLOCK";
export const SET_TEMP_POSITION = "SET_TEMP_POSITION";
export const SET_MODE = "SET_MODE";
export const ADD_GOVERMENT = "ADD_GOVERMENT";
export const SELECT_GOVERMENT = "SELECT_GOVERMENT";
export const DELETE_GOVERMENT = "DELETE_GOVERMENT";
export const EDIT_GOVERMENT = "EDIT_GOVERMENT";
export const SET_ROLES = "SET_ROLES";
export const SET_EMPLOYIES = "SET_EMPLOYIES";
export const SET_USERS = "SET_USERS";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const DELETE_ROLE = "DELETE_ROLE";
export const SET_EMPLOYEE_REPLACEMENT = "SET_EMPLOYEE_REPLACEMENT";
export const SET_ALL_GOVERMENT_AGENCIES = "SET_ALL_GOVERMENT_AGENCIES";
export const SET_SUBDIVISION_UNDER_GA = "SET_SUBDIVISION_UNDER_GA";
export const SEND_TO_APPLY = "SEND_TO_APPLY";
export const SEND_TO_REJECT = "SEND_TO_REJECT";
export const SET_GA_STATE = "SET_GA_STATE";

// LogsStore

export const SET_LOGS = "SET_LOGS";
export const SET_LOGS_LOADING = "SET_LOGS_LOADING";
