//TreeStore
export const SET_TREE = "SET_TREE";
export const INSERT_NODE_TO_TREE = "INSERT_NODE_TO_TREE";
export const UPDATE_TREE = "UPDATE_TREE";
export const DELETE_NODE = "DELETE_NODE";
export const DELETE_POSITION_FROM_NODE = "DELETE_POSITION_FROM_NODE";
export const SET_DRAG_TREE = "SET_DRAG_TREE";
export const INSERT_POSITION_TO_NODE = "INSERT_POSITION_TO_NODE";
export const SET_PLUS_SELECTED_NODE = "SET_PLUS_SELECTED_NODE";
export const ADD_SUBDIVISION = "ADD_SUBDIVISION";
export const DELETE_ROLE_FROM_TREE = "DELETE_ROLE_FROM_TREE";
//SystemStore
export const SET_USER_TYPE = "SET_USER_TYPE";
//HomeStpre
export const SET_POSITIONS = "SET_POSITIONS";
export const ADD_POSITION = "ADD_POSITION";
export const DELETE_POSITION = "DELETE_POSITION";
export const GET_FILTERED_POSITIONS = "GET_FILTERED_POSITIONS";
export const SET_UNLOCK = "SET_UNLOCK";
export const SET_TEMP_POSITION = "SET_TEMP_POSITION";
export const SET_MODE = "SET_MODE";
export const ADD_GOVERMENT = "ADD_GOVERMENT";
export const SELECT_GOVERMENT = "SELECT_GOVERMENT";
export const DELETE_GOVERMENT = "DELETE_GOVERMENT";
export const EDIT_GOVERMENT = "EDIT_GOVERMENT";
export const SET_ROLES = "SET_ROLES";
export const SET_EMPLOYIES = "SET_EMPLOYIES";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const DELETE_ROLE = "DELETE_ROLE";
export const SET_EMPLOYEE_TO_TEMP_POSITION = "SET_EMPLOYEE_TO_TEMP_POSITION";
export const SET_ALL_GOVERMENT_AGENCIES = "SET_ALL_GOVERMENT_AGENCIES";
export const SET_SUBDIVISION_UNDER_GA = "SET_SUBDIVISION_UNDER_GA";
